export interface Programa {
  numeroDeTarea: number;
  link: string;
  nombre: string;
  fechaDeEntrega: string;
  reseña: string;
  zipLink: string;
  ytLink: string;
  githubLink: string;
}
export const programas: Programa[] = [
  { numeroDeTarea: 2, 
    link: 'https://semsotarea16.s3.amazonaws.com/RodriguezAlanD01Act2.pdf', 
    nombre: 'Simulación de Procesamiento por Lotes', 
    fechaDeEntrega:'4 de Febrero de 2022',
    reseña: 'Esta actividad consistió en simular el procesamiento por lotes básico.',
    zipLink: 'https://drive.google.com/file/d/1-9hwWm8El2p9Ofd99XaqsmcqQgetbQox/view?usp=sharing',
    ytLink: 'https://www.youtube.com/embed/BKlGDQt600E',
    githubLink: 'https://github.com/Alan-Rodz/Python/blob/master/SemSOTarea2.py',
  },
  { numeroDeTarea: 4, 
    link: 'https://semsotarea16.s3.amazonaws.com/RodriguezAlanD01Act4.pdf', 
    nombre: 'Simulación del Procesamiento por Lotes con Multiprogramación', 
    fechaDeEntrega:'18 de Febrero de 2022',
    reseña: 'En esta entrega se extienden las capacidades del programa anterior para soportar la multiprogramación.',
    zipLink: 'https://drive.google.com/file/d/1Jyv67COGv9kJPwHIzXKx_0nX4oJiTU6F/view?usp=sharing',
    ytLink: 'https://www.youtube.com/embed/BKlGDQt600E',
    githubLink: 'https://github.com/Alan-Rodz/SemSOTarea4',
  },
  { numeroDeTarea: 6, 
    link: 'https://semsotarea16.s3.amazonaws.com/RodriguezAlanD01Act6.pdf', 
    nombre: 'Simulador de Sistema Operativo con algoritmo FCFS', 
    fechaDeEntrega:'4 de Marzo de 2022',
    reseña: 'En esta entrega se modifica el programa simulador de Sistema Operativo para que funcione haciendo uso del algoritmo FCFS (First Come, First Serve)',
    zipLink: 'https://drive.google.com/file/d/1r72OhJfPBjhut5ZgtGZMD3h4UF7Gg3_3/view?usp=sharing',
    ytLink: 'https://www.youtube.com/embed/c8ycUy8mknM',
    githubLink: 'https://github.com/Alan-Rodz/SemSOTarea6',
  },
  { numeroDeTarea: 8, 
    link: 'https://semsotarea16.s3.amazonaws.com/RodriguezAlanD01Act8.pdf', 
    nombre: 'Continuación del Simulador de Sistema Operativo con FCFS', 
    fechaDeEntrega:'18 de Marzo de 2021',
    reseña: 'Se continua expandiendo el programa anterior, esta vez agregando nuevas teclas cuya funcionalidad modifica el comportamiento del programa.',
    zipLink: 'https://drive.google.com/file/d/1Im2_vh0aj6CAg9T9gVonBzGkhPQFQLix/view?usp=sharing',
    ytLink: 'https://www.youtube.com/embed/bvcJCKd8OZ4',
    githubLink: 'https://github.com/Alan-Rodz/SemSOTarea8',
  },
  { numeroDeTarea: 10, 
    link: 'https://semsotarea16.s3.amazonaws.com/RodriguezAlanD01Act10.pdf', 
    nombre: 'Simulador de Sistema Operativo con algoritmo Round Robin', 
    fechaDeEntrega:'1 de Abril de 2022',
    reseña: 'En esta ocasión se modifica el programa simulador de Sistema Operativo para que funcione haciendo uso del algoritmo de planificación Round Robin.',
    zipLink: 'https://drive.google.com/file/d/1wwLMp4I5NvBXlRuRVRlFn6YGOrP4wdHD/view?usp=sharing',
    ytLink: 'https://www.youtube.com/embed/mWBBm-x5eC0',
    githubLink: 'https://github.com/Alan-Rodz/SemSOTarea10',
  },
  { numeroDeTarea: 12, 
    link: 'https://semsotarea16.s3.amazonaws.com/RodriguezAlanD01Act12.pdf', 
    nombre: 'Programa Productor - Consumidor', 
    fechaDeEntrega: '29 de Abril de 2021',
    reseña: 'Este programa ejemplifica la relación Productor - Consumidor',
    zipLink: 'https://drive.google.com/file/d/1-9hwWm8El2p9Ofd99XaqsmcqQgetbQox/view?usp=sharing',
    ytLink: 'https://www.youtube.com/embed/WBN8viqHHKk',
    githubLink: 'https://github.com/Alan-Rodz/SemSOTarea12',
  },
  { numeroDeTarea: 16, 
    link: '', 
    nombre: 'Portafolio de Evidencias del Curso', 
    fechaDeEntrega: '20 de Mayo de 2022',
    reseña: 'En esta actividad se hace un portafolio donde se incluye la información de todos los trabajos realizados a lo largo del curso.',
    zipLink: '',
    ytLink: '',
    githubLink: 'https://github.com/Alan-Rodz/SemSOTarea16',
  },

]